# Site Metadata
title: Prompt Engineering Holy Grail
description: A comprehensive resource for prompt engineering best practices and techniques.
url: "https://zacfrulloni.github.io/Prompt-Engineering-Holy-Grail" # Replace with your actual GitHub Pages URL
baseurl: "" # If your site is at the root, leave this empty. If it's under a subpath, e.g., /blog, set accordingly.

author:
  name: Zac Frulloni
  email: zacfrull@hotmail.com # Replace with your actual email

# Theme Configuration
theme: minima # You can change this to another supported theme if desired

# Plugins (Optional but Recommended)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude Files from Processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Permalink Structure
permalink: /:categories/:year/:month/:day/:title/
markdown: GFM
